-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 15:39:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema anime_central_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `anime_central_db` ;

-- -----------------------------------------------------
-- Schema anime_central_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anime_central_db` DEFAULT CHARACTER SET utf8 ;
USE `anime_central_db` ;

-- -----------------------------------------------------
-- Table `anime_central_db`.`Anime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Anime` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Anime` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `picture` LONGBLOB NULL,
  `date_aired` DATE NULL,
  `total_score` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Genre` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeGenre` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeGenre` (
  `anime_id` INT UNSIGNED NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `genre_id`),
  INDEX `fk_Anime_has_Genre_Genre1_idx` (`genre_id` ASC) VISIBLE,
  INDEX `fk_Anime_has_Genre_Anime_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Genre_Anime`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Genre_Genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `anime_central_db`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Studio` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Studio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Producer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Producer` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Producer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Licencor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Licencor` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Licencor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeStudio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeStudio` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeStudio` (
  `anime_id` INT UNSIGNED NOT NULL,
  `studio_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `studio_id`),
  INDEX `fk_Anime_has_Studio_Studio1_idx` (`studio_id` ASC) VISIBLE,
  INDEX `fk_Anime_has_Studio_Anime1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Studio_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Studio_Studio1`
    FOREIGN KEY (`studio_id`)
    REFERENCES `anime_central_db`.`Studio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeProducer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeProducer` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeProducer` (
  `anime_id` INT UNSIGNED NOT NULL,
  `producer_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `producer_id`),
  INDEX `fk_Anime_has_Producer_Producer1_idx` (`producer_id` ASC) VISIBLE,
  INDEX `fk_Anime_has_Producer_Anime1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Producer_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Producer_Producer1`
    FOREIGN KEY (`producer_id`)
    REFERENCES `anime_central_db`.`Producer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeLicencor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeLicencor` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeLicencor` (
  `anime_id` INT UNSIGNED NOT NULL,
  `licencor_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `licencor_id`),
  INDEX `fk_Anime_has_Licencor_Licencor1_idx` (`licencor_id` ASC) VISIBLE,
  INDEX `fk_Anime_has_Licencor_Anime1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Licencor_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Licencor_Licencor1`
    FOREIGN KEY (`licencor_id`)
    REFERENCES `anime_central_db`.`Licencor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`User` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`User` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserScore` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserScore` (
  `user_username` VARCHAR(20) NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  `score` FLOAT NULL,
  PRIMARY KEY (`user_username`, `anime_id`),
  INDEX `fk_User_has_Anime_Anime1_idx` (`anime_id` ASC) VISIBLE,
  INDEX `fk_User_has_Anime_User1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Anime_User1`
    FOREIGN KEY (`user_username`)
    REFERENCES `anime_central_db`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Anime_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserComment` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserComment` (
  `id` INT NOT NULL,
  `user_username` VARCHAR(20) NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  `Comment` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`, `user_username`, `anime_id`),
  INDEX `fk_Anime_has_User_User1_idx` (`user_username` ASC) VISIBLE,
  INDEX `fk_Anime_has_User_Anime1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_User_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_User_User1`
    FOREIGN KEY (`user_username`)
    REFERENCES `anime_central_db`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserWatched`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserWatched` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserWatched` (
  `user_username` VARCHAR(20) NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_username`, `anime_id`),
  INDEX `fk_User_has_Anime_Anime2_idx` (`anime_id` ASC) VISIBLE,
  INDEX `fk_User_has_Anime_User2_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Anime_User2`
    FOREIGN KEY (`user_username`)
    REFERENCES `anime_central_db`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Anime_Anime2`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserWish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserWish` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserWish` (
  `user_username` VARCHAR(20) NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_username`, `anime_id`),
  INDEX `fk_Anime_has_User_User2_idx` (`user_username` ASC) VISIBLE,
  INDEX `fk_Anime_has_User_Anime2_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_User_Anime2`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_User_User2`
    FOREIGN KEY (`user_username`)
    REFERENCES `anime_central_db`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Episode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Episode` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Episode` (
  `number_of_episode` INT NOT NULL,
  `Anime_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`number_of_episode`, `Anime_id`),
  INDEX `fk_Episode_Anime1_idx` (`Anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_Episode_Anime1`
    FOREIGN KEY (`Anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
