-- MySQL Script generated by MySQL Workbench
-- Sun May 17 15:21:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema anime_central_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `anime_central_db` ;

-- -----------------------------------------------------
-- Schema anime_central_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anime_central_db` DEFAULT CHARACTER SET utf8 ;
USE `anime_central_db` ;

-- -----------------------------------------------------
-- Table `anime_central_db`.`Anime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Anime` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Anime` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `picture` LONGBLOB NULL,
  `date_aired` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Genre` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeGenre` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeGenre` (
  `anime_id` INT UNSIGNED NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `genre_id`),
  INDEX `fk_Anime_has_Genre_Genre1_idx` (`genre_id` ASC),
  INDEX `fk_Anime_has_Genre_Anime_idx` (`anime_id` ASC),
  CONSTRAINT `fk_Anime_has_Genre_Anime`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Genre_Genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `anime_central_db`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Studio` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Studio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Producer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Producer` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Producer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Licencor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Licencor` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Licencor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeStudio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeStudio` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeStudio` (
  `anime_id` INT UNSIGNED NOT NULL,
  `studio_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `studio_id`),
  INDEX `fk_Anime_has_Studio_Studio1_idx` (`studio_id` ASC),
  INDEX `fk_Anime_has_Studio_Anime1_idx` (`anime_id` ASC),
  CONSTRAINT `fk_Anime_has_Studio_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Studio_Studio1`
    FOREIGN KEY (`studio_id`)
    REFERENCES `anime_central_db`.`Studio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeProducer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeProducer` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeProducer` (
  `anime_id` INT UNSIGNED NOT NULL,
  `producer_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `producer_id`),
  INDEX `fk_Anime_has_Producer_Producer1_idx` (`producer_id` ASC),
  INDEX `fk_Anime_has_Producer_Anime1_idx` (`anime_id` ASC),
  CONSTRAINT `fk_Anime_has_Producer_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Producer_Producer1`
    FOREIGN KEY (`producer_id`)
    REFERENCES `anime_central_db`.`Producer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`AnimeLicencor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeLicencor` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeLicencor` (
  `anime_id` INT UNSIGNED NOT NULL,
  `licencor_id` INT NOT NULL,
  PRIMARY KEY (`anime_id`, `licencor_id`),
  INDEX `fk_Anime_has_Licencor_Licencor1_idx` (`licencor_id` ASC),
  INDEX `fk_Anime_has_Licencor_Anime1_idx` (`anime_id` ASC),
  CONSTRAINT `fk_Anime_has_Licencor_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Licencor_Licencor1`
    FOREIGN KEY (`licencor_id`)
    REFERENCES `anime_central_db`.`Licencor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`User` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserScore` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserScore` (
  `user_id` INT NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  `score` FLOAT NULL,
  PRIMARY KEY (`user_id`, `anime_id`),
  INDEX `fk_User_has_Anime_Anime1_idx` (`anime_id` ASC),
  CONSTRAINT `fk_User_has_Anime_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `anime_central_db`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Anime_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserComment` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserComment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  `Comment` MEDIUMTEXT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`, `user_id`, `anime_id`),
  INDEX `fk_Anime_has_User_Anime1_idx` (`anime_id` ASC),
  INDEX `fk_Anime_has_User_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Anime_has_User_Anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `anime_central_db`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserWatched`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserWatched` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserWatched` (
  `user_id` INT NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `anime_id`),
  INDEX `fk_User_has_Anime_Anime2_idx` (`anime_id` ASC),
  CONSTRAINT `fk_User_has_Anime_User2`
    FOREIGN KEY (`user_id`)
    REFERENCES `anime_central_db`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Anime_Anime2`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`UserWish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`UserWish` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`UserWish` (
  `user_id` INT NOT NULL,
  `anime_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `anime_id`),
  INDEX `fk_Anime_has_User_Anime2_idx` (`anime_id` ASC),
  CONSTRAINT `fk_Anime_has_User_Anime2`
    FOREIGN KEY (`anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_User_User2`
    FOREIGN KEY (`user_id`)
    REFERENCES `anime_central_db`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anime_central_db`.`Episode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`Episode` ;

CREATE TABLE IF NOT EXISTS `anime_central_db`.`Episode` (
  `number_of_episode` INT NOT NULL,
  `Anime_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`number_of_episode`, `Anime_id`),
  INDEX `fk_Episode_Anime1_idx` (`Anime_id` ASC),
  CONSTRAINT `fk_Episode_Anime1`
    FOREIGN KEY (`Anime_id`)
    REFERENCES `anime_central_db`.`Anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `anime_central_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `anime_central_db`.`AnimeTotalScore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeTotalScore` (`anime_id` INT, `'total_score'` INT);

-- -----------------------------------------------------
-- Placeholder table for view `anime_central_db`.`AnimeTotalViews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anime_central_db`.`AnimeTotalViews` (`anime_id` INT, `'total_views'` INT);

-- -----------------------------------------------------
-- View `anime_central_db`.`AnimeTotalScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeTotalScore`;
DROP VIEW IF EXISTS `anime_central_db`.`AnimeTotalScore` ;
USE `anime_central_db`;
CREATE  OR REPLACE VIEW `AnimeTotalScore` AS
SELECT anime_id, AVG(score) AS 'total_score' 
FROM UserScore 
GROUP BY anime_id;

-- -----------------------------------------------------
-- View `anime_central_db`.`AnimeTotalViews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anime_central_db`.`AnimeTotalViews`;
DROP VIEW IF EXISTS `anime_central_db`.`AnimeTotalViews` ;
USE `anime_central_db`;
CREATE  OR REPLACE VIEW `AnimeTotalViews` AS
SELECT anime_id, COUNT(*) AS 'total_views' 
FROM UserWatched
GROUP BY anime_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `anime_central_db`.`Anime`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Monster', 'Dr. Kenzou Tenma, an elite neurosurgeon recently engaged to his hospital director\'s daughter, is well on his way to ascending the hospital hierarchy. That is until one night, a seemingly small event changes Dr. Tenma\'s life forever. While preparing to perform surgery on someone, he gets a call from the hospital director telling him to switch patients and instead perform life-saving brain surgery on a famous performer. His fellow doctors, fiancée, and the hospital director applaud his accomplishment; but because of the switch, a poor immigrant worker is dead, causing Dr. Tenma to have a crisis of conscience.', NULL, '2004-04-07');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'JoJo\'s Bizarre Adventure', 'In 1868, Dario Brando saves the life of an English nobleman, George Joestar. By taking in Dario\'s son Dio when the boy becomes fatherless, George hopes to repay the debt he owes to his savior. However Dio, unsatisfied with his station in life, aspires to seize the Joestar house for his own. Wielding an Aztec stone mask with supernatural properties, he sets out to destroy George and his son, Jonathan \"JoJo\" Joestar, and triggers a chain of events that will continue to echo through the years to come.', NULL, '2012-10-06');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Attack on Titan ', 'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.', NULL, '2013-04-07');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Vandred', 'In Vandread, men are from Mars and women are from Venus! Well, not quite. Technology has allowed mankind to colonize the entire Milky Way galaxy, and in one star system, the men and women live on two different planets, Taraak and Mejere. A bitter and very literal gender war rages, to the point where they don\'t even see each other as the sames species anymore!', NULL, '2000-10-03');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Naruto', 'Moments prior to Naruto Uzumaki\'s birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc. In order to put an end to the Kyuubi\'s rampage, the leader of the village, the Fourth Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto.', NULL, '2002-10-03');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'One Piece', 'Gol D. Roger was known as the \"Pirate King,\" the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King.', NULL, '1999-10-20');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Fairy Tail', 'In the mystical land of Fiore, magic exists as an essential part of everyday life. Countless magic guilds lie at the core of all magical activity, and serve as venues for like-minded mages to band together and take on job requests. Among them, Fairy Tail stands out from the rest as a place of strength, spirit, and family.', NULL, '2009-10-12');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Death Note', 'A shinigami, as a god of death, can kill any person—provided they see their victim\'s face and write their victim\'s name in a notebook called a Death Note. One day, Ryuk, bored by the shinigami lifestyle and interested in seeing how a human would use a Death Note, drops one into the human realm.', NULL, '2006-10-04');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Bleach', 'Ichigo Kurosaki is an ordinary high schooler—until his family is attacked by a Hollow, a corrupt spirit that seeks to devour human souls. It is then that he meets a Soul Reaper named Rukia Kuchiki, who gets injured while protecting Ichigo\'s family from the assailant. To save his family, Ichigo accepts Rukia\'s offer of taking her powers and becomes a Soul Reaper as a result.', NULL, '2004-10-05');
INSERT INTO `anime_central_db`.`Anime` (`id`, `name`, `description`, `picture`, `date_aired`) VALUES (DEFAULT, 'Digimon Adventure', 'When a group of kids head out for summer camp, they don\'t expect it to snow in the middle of July. Out of nowhere, the kids receive strange devices which transport them to a very different world to begin their Digimon Adventure! Led by the plucky Taichi Yagami, the seven children must now survive in a realm far from home, filled with monsters and devoid of other humans.', NULL, '1999-03-07');

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`Genre`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'action', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'adventure', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'comedy', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'shounen', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'super power', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'matrial arts', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'magic', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'fantasy', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'supernatural', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'kids', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'vampire', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'echi', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'mecha', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'sci-fi', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'space', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'mystery', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'police', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'psychological', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'thriller', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'drama', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'horror', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'seinen', NULL);
INSERT INTO `anime_central_db`.`Genre` (`id`, `name`, `description`) VALUES (DEFAULT, 'military', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`AnimeGenre`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (5, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (5, 2);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (5, 3);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (5, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (5, 5);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (5, 6);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (7, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (7, 2);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (7, 3);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (7, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (7, 7);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (7, 8);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (9, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (9, 2);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (9, 3);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (9, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (9, 5);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (9, 9);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (1, 20);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (1, 21);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (1, 16);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (1, 17);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (1, 18);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (1, 22);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (1, 19);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (2, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (2, 2);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (2, 9);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (2, 11);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (2, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (3, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (3, 23);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (3, 16);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (3, 5);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (3, 20);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (3, 8);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (3, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (4, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (4, 12);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (4, 13);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (4, 14);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (4, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (4, 15);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (8, 16);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (8, 17);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (8, 18);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (8, 9);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (8, 19);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (8, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (6, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (6, 2);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (6, 3);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (6, 4);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (6, 5);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (6, 20);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (6, 8);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (10, 1);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (10, 2);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (10, 3);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (10, 8);
INSERT INTO `anime_central_db`.`AnimeGenre` (`anime_id`, `genre_id`) VALUES (10, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`Studio`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'Studio Pierrot');
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'Satelight');
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'A-1 Pictures');
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'Madhouse');
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'David Production');
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'Wit Studio');
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'Gonzo');
INSERT INTO `anime_central_db`.`Studio` (`id`, `name`) VALUES (DEFAULT, 'Toei Animation');

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`Producer`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'TV Tokyo');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Aniplex');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Shueisha');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Dentsu');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'TV Tokyo Music');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Studio Kelmadick');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Pony Canyon');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Kodansha');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'DAX Production');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Sakura Create');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'VAP');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Shogakukan Productions');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Nippon Television Network');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Yomiko Advertising');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Warner Bros. Japan');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Kamikaze Douga');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'KlockWorx');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Production I.G.');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Mainichi Broadcasting System');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Pony Canyon Enterprise');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'GDH');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Media Factory');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Fuji TV');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'TAP');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Konami');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Ashi Production');
INSERT INTO `anime_central_db`.`Producer` (`id`, `name`) VALUES (DEFAULT, 'Mad Box');

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`Licencor`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`Licencor` (`id`, `name`) VALUES (DEFAULT, 'Viz Media');
INSERT INTO `anime_central_db`.`Licencor` (`id`, `name`) VALUES (DEFAULT, 'Funimation');
INSERT INTO `anime_central_db`.`Licencor` (`id`, `name`) VALUES (DEFAULT, 'Warner Bros. Pictures');
INSERT INTO `anime_central_db`.`Licencor` (`id`, `name`) VALUES (DEFAULT, 'Geneon Entertainment USA');
INSERT INTO `anime_central_db`.`Licencor` (`id`, `name`) VALUES (DEFAULT, '4Kids Entertainment');
INSERT INTO `anime_central_db`.`Licencor` (`id`, `name`) VALUES (DEFAULT, 'Saban Entertainment');
INSERT INTO `anime_central_db`.`Licencor` (`id`, `name`) VALUES (DEFAULT, 'Flatiron Film Company');

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`AnimeStudio`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (5, 1);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (7, 1);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (9, 2);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (9, 3);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (1, 4);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (2, 5);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (3, 6);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (4, 7);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (6, 8);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (8, 4);
INSERT INTO `anime_central_db`.`AnimeStudio` (`anime_id`, `studio_id`) VALUES (10, 8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`AnimeProducer`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (5, 1);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (5, 2);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (5, 3);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (7, 1);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (7, 2);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (7, 3);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (7, 4);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (7, 5);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (7, 6);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (9, 1);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (9, 4);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (9, 7);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (9, 8);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (9, 9);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (9, 10);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (1, 11);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (1, 12);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (1, 13);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (2, 14);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (2, 15);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (2, 16);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (2, 17);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (2, 3);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (3, 18);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (3, 4);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (3, 19);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (3, 7);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (3, 8);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (3, 27);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (3, 20);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (4, 21);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (4, 4);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (4, 22);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (6, 23);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (6, 24);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (6, 3);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (8, 11);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (8, 25);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (8, 26);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (8, 13);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (8, 3);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (10, 14);
INSERT INTO `anime_central_db`.`AnimeProducer` (`anime_id`, `producer_id`) VALUES (10, 23);

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`AnimeLicencor`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (5, 1);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (7, 2);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (9, 1);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (1, 1);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (2, 1);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (2, 3);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (3, 2);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (4, 2);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (4, 4);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (6, 2);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (6, 5);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (8, 1);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (10, 6);
INSERT INTO `anime_central_db`.`AnimeLicencor` (`anime_id`, `licencor_id`) VALUES (10, 7);

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`User` (`id`, `username`, `password`, `email`) VALUES (DEFAULT, 'DatabaseAdministrator', 'Admin1', 'petar.b.zecevic@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`UserScore`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`UserScore` (`user_id`, `anime_id`, `score`) VALUES (1, 1, 10);
INSERT INTO `anime_central_db`.`UserScore` (`user_id`, `anime_id`, `score`) VALUES (1, 3, 10);
INSERT INTO `anime_central_db`.`UserScore` (`user_id`, `anime_id`, `score`) VALUES (1, 5, 9);
INSERT INTO `anime_central_db`.`UserScore` (`user_id`, `anime_id`, `score`) VALUES (1, 7, 8);
INSERT INTO `anime_central_db`.`UserScore` (`user_id`, `anime_id`, `score`) VALUES (1, 8, 10);
INSERT INTO `anime_central_db`.`UserScore` (`user_id`, `anime_id`, `score`) VALUES (1, 10, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`UserComment`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`UserComment` (`id`, `user_id`, `anime_id`, `Comment`, `date`) VALUES (DEFAULT, 1, 1, 'Munch munch, chomp chomp, gobble gobble, gulp...', '2016-10-01');
INSERT INTO `anime_central_db`.`UserComment` (`id`, `user_id`, `anime_id`, `Comment`, `date`) VALUES (DEFAULT, 1, 3, 'Titans have built the Walls to protect themselves from Levi', '2014-03-20');
INSERT INTO `anime_central_db`.`UserComment` (`id`, `user_id`, `anime_id`, `Comment`, `date`) VALUES (DEFAULT, 1, 5, 'Weakness disgusts me.', '2014-02-13');
INSERT INTO `anime_central_db`.`UserComment` (`id`, `user_id`, `anime_id`, `Comment`, `date`) VALUES (DEFAULT, 1, 7, 'Mystogan is the best!', '2013-09-04');
INSERT INTO `anime_central_db`.`UserComment` (`id`, `user_id`, `anime_id`, `Comment`, `date`) VALUES (DEFAULT, 1, 8, 'I\'ll take a potato chip...', '2014-12-11');
INSERT INTO `anime_central_db`.`UserComment` (`id`, `user_id`, `anime_id`, `Comment`, `date`) VALUES (DEFAULT, 1, 10, 'Digimon ce te pratiti! Vi ste tim za sva vremena!', '2005-04-04');

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`UserWatched`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`UserWatched` (`user_id`, `anime_id`) VALUES (1, 1);
INSERT INTO `anime_central_db`.`UserWatched` (`user_id`, `anime_id`) VALUES (1, 3);
INSERT INTO `anime_central_db`.`UserWatched` (`user_id`, `anime_id`) VALUES (1, 5);
INSERT INTO `anime_central_db`.`UserWatched` (`user_id`, `anime_id`) VALUES (1, 7);
INSERT INTO `anime_central_db`.`UserWatched` (`user_id`, `anime_id`) VALUES (1, 8);
INSERT INTO `anime_central_db`.`UserWatched` (`user_id`, `anime_id`) VALUES (1, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `anime_central_db`.`UserWish`
-- -----------------------------------------------------
START TRANSACTION;
USE `anime_central_db`;
INSERT INTO `anime_central_db`.`UserWish` (`user_id`, `anime_id`) VALUES (1, 2);
INSERT INTO `anime_central_db`.`UserWish` (`user_id`, `anime_id`) VALUES (1, 4);
INSERT INTO `anime_central_db`.`UserWish` (`user_id`, `anime_id`) VALUES (1, 6);
INSERT INTO `anime_central_db`.`UserWish` (`user_id`, `anime_id`) VALUES (1, 9);

COMMIT;

